name: Test runner clock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: swift-build-windows-latest-32-cores

    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/SourceCache/cmake
    - run: |
        echo %DATE% %TIME%
