name: Test runner clock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: swift-build-windows-latest-32-cores

    steps:
    - run: |
        Write-Output "Current Date and Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzzz')"
